import { transactionService } from "./data/transactionService.js";
const state={transactions:[],month:new Date(2026,8,1),selectedDate:"2026-09-19",view:"calendar"};
const $=id=>document.getElementById(id);
const dateKey=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");
const money=(v,c="AED")=>c+" "+Number(v).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function row(tx){const sign=tx.type==="Expense"?"-":tx.type==="Income"?"+":"";const cls=tx.type==="Expense"?"expense":tx.type==="Income"?"income":"";return `<article class="transaction-row"><div class="tx-icon">${tx.type==="Expense"?"↑":tx.type==="Income"?"↓":"↔"}</div><div><div class="tx-title">${esc(tx.merchant)}</div><div class="tx-meta">${esc(tx.date)} · ${esc(tx.category)} · ${esc(tx.account)} · ${esc(tx.owner)}</div>${tx.category==="Needs Review"?'<span class="tx-review">Needs Review</span>':""}</div><div class="tx-amount ${cls}">${sign}${Number(tx.amount).toFixed(2)}</div></article>`;}
function monthTx(){const y=state.month.getFullYear(),m=state.month.getMonth()+1;return state.transactions.filter(t=>{const [a,b]=t.date.split("-").map(Number);return a===y&&b===m})}
function summary(){let i=0,e=0;monthTx().forEach(t=>{if(t.type==="Income")i+=t.amount;if(t.type==="Expense")e+=t.amount});$("incomeTotal").textContent=money(i);$("expenseTotal").textContent=money(e);$("netTotal").textContent=money(i-e)}
function calendar(){const y=state.month.getFullYear(),m=state.month.getMonth(),g=$("calendarGrid");$("monthLabel").textContent=state.month.toLocaleDateString("en-US",{month:"long",year:"numeric"});g.innerHTML="";for(let i=0;i<new Date(y,m,1).getDay();i++)g.insertAdjacentHTML("beforeend",'<div class="day-cell muted"></div>');for(let d=1;d<=new Date(y,m+1,0).getDate();d++){const k=dateKey(new Date(y,m,d)),daily=state.transactions.filter(t=>t.date===k),exp=daily.filter(t=>t.type==="Expense").reduce((s,t)=>s+t.amount,0),b=document.createElement("button");b.className="day-cell"+(k===state.selectedDate?" selected":"")+(k===dateKey(new Date())?" today":"");b.innerHTML=`<div class="day-number">${d}</div>${exp?`<div class="day-total">${Math.round(exp)}</div>`:""}`;b.onclick=()=>{state.selectedDate=k;calendar();dayList()};g.appendChild(b)}}
function dayList(){const d=new Date(state.selectedDate+"T00:00:00");$("selectedDateLabel").textContent=d.toLocaleDateString("en-US",{weekday:"long",day:"numeric",month:"long"});const a=state.transactions.filter(t=>t.date===state.selectedDate);$("transactionList").innerHTML=a.length?a.map(row).join(""):'<div class="empty-state">No transactions for this day.</div>'}
function allList(){const q=$("searchInput").value.toLowerCase(),type=$("typeFilter").value,owner=$("ownerFilter").value;const a=[...state.transactions].filter(t=>(!type||t.type===type)&&(!owner||t.owner===owner)&&(!q||[t.merchant,t.category,t.account].some(x=>String(x).toLowerCase().includes(q)))).sort((a,b)=>b.date.localeCompare(a.date));$("allTransactions").innerHTML=a.length?a.map(row).join(""):'<div class="empty-state">No matching transactions.</div>'}
function reviews(){const a=state.transactions.filter(t=>t.category==="Needs Review");$("reviewCount").textContent=a.length;$("reviewTransactions").innerHTML=a.length?a.map(row).join(""):'<div class="empty-state success-state">✓ Nothing needs review.</div>'}
function render(){summary();calendar();dayList();allList();reviews()}
function showView(v){state.view=v;["calendarView","transactionsView","reviewView","placeholderView"].forEach(id=>$(id).classList.add("hidden"));const map={calendar:"calendarView",transactions:"transactionsView",review:"reviewView"};$(map[v]||"placeholderView").classList.remove("hidden");$("pageTitle").textContent=v[0].toUpperCase()+v.slice(1);$("todayBtn").classList.toggle("hidden",v!=="calendar");document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="transactions")allList();if(v==="review")reviews()}
async function refresh(){state.transactions=await transactionService.list();render()}
$("prevMonthBtn").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);state.selectedDate=dateKey(state.month);render()};
$("nextMonthBtn").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);state.selectedDate=dateKey(state.month);render()};
$("todayBtn").onclick=()=>{const n=new Date();state.month=new Date(n.getFullYear(),n.getMonth(),1);state.selectedDate=dateKey(n);render()};
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));
["searchInput","typeFilter","ownerFilter"].forEach(id=>$(id).addEventListener(id==="searchInput"?"input":"change",allList));
function openAdd(){ $("txDate").value=state.selectedDate;$("transactionDialog").showModal()}
document.querySelectorAll(".add-trigger").forEach(b=>b.onclick=openAdd);
$("closeDialog").onclick=$("cancelDialog").onclick=()=>$("transactionDialog").close();
$("transactionForm").onsubmit=async e=>{e.preventDefault();const tx={date:$("txDate").value,owner:$("txOwner").value,type:$("txType").value,account:$("txAccount").value,merchant:$("txMerchant").value,amount:$("txAmount").value,currency:$("txCurrency").value,category:$("txCategory").value};await transactionService.add(tx);state.selectedDate=tx.date;const [y,m]=tx.date.split("-").map(Number);state.month=new Date(y,m-1,1);e.target.reset();$("transactionDialog").close();await refresh()};
refresh();